/**:
  ros__parameters:
    basic:
      map_frame: "camera_init"
      robot_frame: "body"
      loop_update_hz: 2.0
      vis_hz: 1.0

    input:
      # FAST-LIO publishes these topics for MID360 mapping.
      odom_topic: "Odometry_loc"
      cloud_topic: "cloud_registered_1"
      cloud_is_in_world_frame: true
      sync_queue_size: 20

    output:
      corrected_odom_topic: "corrected_odom"
      corrected_path_topic: "corrected_path"
      original_odom_topic: "ori_odom"
      original_path_topic: "ori_path"
      corrected_map_topic: "corrected_map"
      corrected_current_pcd_topic: "corrected_current_pcd"
      loop_detection_topic: "loop_detection"
      realtime_pose_topic: "pose_stamped"
      debug_src_topic: "src"
      debug_dst_topic: "dst"
      debug_coarse_aligned_topic: "coarse_aligned_quatro"
      debug_fine_aligned_topic: "fine_aligned_nano_gicp"
      save_trigger_topic: "save_dir"
      publish_corrected_map_continuously: true
      transient_qos_depth: 10
      realtime_qos_depth: 10
      save_trigger_qos_depth: 1

    keyframe:
      keyframe_threshold: 1.0
      max_odom_translation_norm: 10000.0
      max_odom_keyframe_delta: 100.0
      num_submap_keyframes: 10
      enable_submap_matching: false

    quatro_nano_gicp_voxel_resolution: 0.3
    save_voxel_resolution: 0.15
    scancontext_max_correspondence_distance: 35.0

    nano_gicp:
      thread_number: 0
      icp_score_threshold: 1.5
      correspondences_number: 15
      max_correspondence_distance: 35.0
      max_iter: 32
      transformation_epsilon: 0.01
      euclidean_fitness_epsilon: 0.01
      ransac:
        max_iter: 5
        outlier_rejection_threshold: 1.0

    quatro:
      enable: true
      optimize_matching: true
      distance_threshold: 35.0
      max_correspondences: 500
      fpfh_normal_radius: 0.9
      fpfh_radius: 1.5
      estimating_scale: false
      noise_bound: 0.3
      rotation:
        num_max_iter: 50
        gnc_factor: 1.4
        rot_cost_diff_threshold: 0.0001

    result:
      save_map_pcd: false
      save_map_bag: true
      save_in_kitti_format: true
      seq_name: "sequence"
      save_directory: ""
      maps_directory_name: "maps"
      session_name: ""
      session_timestamp_format: "%Y%m%d_%H%M%S"
      scans_directory_name: "scans"
      poses_matrix_filename: "poses_matrix.txt"
      poses_kitti_filename: "poses_kitti.txt"
      poses_tum_filename: "poses_tum.txt"
      scan_file_index_width: 6
      scan_file_extension: ".pcd"
      optimized_map_filename: "map_optimized.pcd"
      raw_map_filename: "map_raw.pcd"
      bag_directory_name: "result_bag"
